title: Smart Home Systems
theme: minima
header_pages:
  - ListOfMedia.md
  - IP.md
  - FreedomOfSpeech.md
  - Privacy.md
  - ComputerNetworkSecurity.md
  - ErrorsFailuresRisks.md
  - WorkAndWealth.md
  - MeetingMinutes.md
